//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limaki.Presenter.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limaki.Presenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap applications_graphics {
            get {
                object obj = ResourceManager.GetObject("applications_graphics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrageRows {
            get {
                object obj = ResourceManager.GetObject("ArrageRows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeBottom {
            get {
                object obj = ResourceManager.GetObject("ArrangeBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeCenter {
            get {
                object obj = ResourceManager.GetObject("ArrangeCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeLeft {
            get {
                object obj = ResourceManager.GetObject("ArrangeLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeMiddle {
            get {
                object obj = ResourceManager.GetObject("ArrangeMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeOneRow {
            get {
                object obj = ResourceManager.GetObject("ArrangeOneRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeRight {
            get {
                object obj = ResourceManager.GetObject("ArrangeRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeSameSize {
            get {
                object obj = ResourceManager.GetObject("ArrangeSameSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeTop {
            get {
                object obj = ResourceManager.GetObject("ArrangeTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeTreeToLeft {
            get {
                object obj = ResourceManager.GetObject("ArrangeTreeToLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrangeTreeToRight {
            get {
                object obj = ResourceManager.GetObject("ArrangeTreeToRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConnectorToolIcon {
            get {
                object obj = ResourceManager.GetObject("ConnectorToolIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CreateWidget24 {
            get {
                object obj = ResourceManager.GetObject("CreateWidget24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap draw_straight_connector_ends_with_arrow16 {
            get {
                object obj = ResourceManager.GetObject("draw_straight_connector_ends_with_arrow16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DrawSelection {
            get {
                object obj = ResourceManager.GetObject("DrawSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap emblem_downloads {
            get {
                object obj = ResourceManager.GetObject("emblem_downloads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FontBoldIcon {
            get {
                object obj = ResourceManager.GetObject("FontBoldIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FontItalicIcon {
            get {
                object obj = ResourceManager.GetObject("FontItalicIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fonts {
            get {
                object obj = ResourceManager.GetObject("fonts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FontUnderlineIcon {
            get {
                object obj = ResourceManager.GetObject("FontUnderlineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap go_next {
            get {
                object obj = ResourceManager.GetObject("go_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap go_previous {
            get {
                object obj = ResourceManager.GetObject("go_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap gohome {
            get {
                object obj = ResourceManager.GetObject("gohome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GraphDocView {
            get {
                object obj = ResourceManager.GetObject("GraphDocView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GraphGraphView {
            get {
                object obj = ResourceManager.GetObject("GraphGraphView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ItemLayout {
            get {
                object obj = ResourceManager.GetObject("ItemLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon LimadaLogo {
            get {
                object obj = ResourceManager.GetObject("LimadaLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon LimadaLogoA {
            get {
                object obj = ResourceManager.GetObject("LimadaLogoA", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LimadaLogoL32 {
            get {
                object obj = ResourceManager.GetObject("LimadaLogoL32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuFileOpenIcon {
            get {
                object obj = ResourceManager.GetObject("MenuFileOpenIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ModifyLayout16 {
            get {
                object obj = ResourceManager.GetObject("ModifyLayout16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ModifyLayout24 {
            get {
                object obj = ResourceManager.GetObject("ModifyLayout24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoveSelectionToolIcon {
            get {
                object obj = ResourceManager.GetObject("MoveSelectionToolIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoveShift {
            get {
                object obj = ResourceManager.GetObject("MoveShift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoveToolIcon {
            get {
                object obj = ResourceManager.GetObject("MoveToolIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap notes {
            get {
                object obj = ResourceManager.GetObject("notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OrderLeftDown {
            get {
                object obj = ResourceManager.GetObject("OrderLeftDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OrderLeftRigh {
            get {
                object obj = ResourceManager.GetObject("OrderLeftRigh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RectangleSelectToolIcon {
            get {
                object obj = ResourceManager.GetObject("RectangleSelectToolIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelectionIcon {
            get {
                object obj = ResourceManager.GetObject("SelectionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Shape {
            get {
                object obj = ResourceManager.GetObject("Shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment {
            get {
                object obj = ResourceManager.GetObject("stock_alignment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_bottom {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_centered {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_centered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_centered_vertically {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_centered_vertically", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_left {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_right {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_alignment_top {
            get {
                object obj = ResourceManager.GetObject("stock_alignment_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_book_blue {
            get {
                object obj = ResourceManager.GetObject("stock_book_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_book_red {
            get {
                object obj = ResourceManager.GetObject("stock_book_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_down_with_subpoints {
            get {
                object obj = ResourceManager.GetObject("stock_down_with_subpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_draw_text {
            get {
                object obj = ResourceManager.GetObject("stock_draw_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_export {
            get {
                object obj = ResourceManager.GetObject("stock_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_first_page {
            get {
                object obj = ResourceManager.GetObject("stock_first_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_form_line_horizontal {
            get {
                object obj = ResourceManager.GetObject("stock_form_line_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_form_table_control {
            get {
                object obj = ResourceManager.GetObject("stock_form_table_control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_bottom {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_center {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_centered {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_centered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_left {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_right {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_graphics_align_top {
            get {
                object obj = ResourceManager.GetObject("stock_graphics_align_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_guides {
            get {
                object obj = ResourceManager.GetObject("stock_guides", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_insert_file {
            get {
                object obj = ResourceManager.GetObject("stock_insert_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_last_page {
            get {
                object obj = ResourceManager.GetObject("stock_last_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_left_with_subpoints {
            get {
                object obj = ResourceManager.GetObject("stock_left_with_subpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_next {
            get {
                object obj = ResourceManager.GetObject("stock_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_next_page {
            get {
                object obj = ResourceManager.GetObject("stock_next_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_previous {
            get {
                object obj = ResourceManager.GetObject("stock_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_previous_page {
            get {
                object obj = ResourceManager.GetObject("stock_previous_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_reload {
            get {
                object obj = ResourceManager.GetObject("stock_reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_right_with_subpoints {
            get {
                object obj = ResourceManager.GetObject("stock_right_with_subpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_fit_height {
            get {
                object obj = ResourceManager.GetObject("stock_table_fit_height", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_fit_width {
            get {
                object obj = ResourceManager.GetObject("stock_table_fit_width", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_fixed {
            get {
                object obj = ResourceManager.GetObject("stock_table_fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_fixed_proportional {
            get {
                object obj = ResourceManager.GetObject("stock_table_fixed_proportional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_same_height {
            get {
                object obj = ResourceManager.GetObject("stock_table_same_height", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_table_same_width {
            get {
                object obj = ResourceManager.GetObject("stock_table_same_width", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stock_up_with_subpoints {
            get {
                object obj = ResourceManager.GetObject("stock_up_with_subpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap StraightConnector {
            get {
                object obj = ResourceManager.GetObject("StraightConnector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stream_save {
            get {
                object obj = ResourceManager.GetObject("stream_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToggleView {
            get {
                object obj = ResourceManager.GetObject("ToggleView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZoomToolIcon {
            get {
                object obj = ResourceManager.GetObject("ZoomToolIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
