namespace Limaki.Tests.Common.Rtf {

    public class RtfTestData {

        public static string WordGame => @"
{\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
{\*\generator Msftedit 5.41.15.1507;}\viewkind4\uc1\pard\f0\fs20 this is a wordgame\par
}
";

        public static string WordGameUmlaut => @"
{\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1031\deflangfe1031{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial{\*\falt Helvetica};}
{\f47\froman\fcharset238\fprq2 Times New Roman CE;}{\f48\froman\fcharset204\fprq2 Times New Roman Cyr;}{\f50\froman\fcharset161\fprq2 Times New Roman Greek;}{\f51\froman\fcharset162\fprq2 Times New Roman Tur;}
{\f52\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f53\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f54\froman\fcharset186\fprq2 Times New Roman Baltic;}{\f55\froman\fcharset163\fprq2 Times New Roman (Vietnamese);}
{\f57\fswiss\fcharset238\fprq2 Arial CE{\*\falt Helvetica};}{\f58\fswiss\fcharset204\fprq2 Arial Cyr{\*\falt Helvetica};}{\f60\fswiss\fcharset161\fprq2 Arial Greek{\*\falt Helvetica};}{\f61\fswiss\fcharset162\fprq2 Arial Tur{\*\falt Helvetica};}
{\f62\fbidi \fswiss\fcharset177\fprq2 Arial (Hebrew){\*\falt Helvetica};}{\f63\fbidi \fswiss\fcharset178\fprq2 Arial (Arabic){\*\falt Helvetica};}{\f64\fswiss\fcharset186\fprq2 Arial Baltic{\*\falt Helvetica};}
{\f65\fswiss\fcharset163\fprq2 Arial (Vietnamese){\*\falt Helvetica};}}{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\green255\blue255;\red0\green255\blue0;\red255\green0\blue255;\red255\green0\blue0;\red255\green255\blue0;
\red255\green255\blue255;\red0\green0\blue128;\red0\green128\blue128;\red0\green128\blue0;\red128\green0\blue128;\red128\green0\blue0;\red128\green128\blue0;\red128\green128\blue128;\red192\green192\blue192;}{\stylesheet{
\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1031\langfe1031\cgrid\langnp1031\langfenp1031 \snext0 Normal;}{\*\cs10 \additive \ssemihidden Default Paragraph Font;}{\*
\ts11\tsrowd\trftsWidthB3\trpaddl108\trpaddr108\trpaddfl3\trpaddft3\trpaddfb3\trpaddfr3\trcbpat1\trcfpat1\tscellwidthfts0\tsvertalt\tsbrdrt\tsbrdrl\tsbrdrb\tsbrdrr\tsbrdrdgl\tsbrdrdgr\tsbrdrh\tsbrdrv 
\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch \af0\afs20 \ltrch \fs20\lang1024\langfe1024\cgrid\langnp1024\langfenp1024 \snext11 \ssemihidden Normal Table;}}{\*\rsidtbl \rsid10506351\rsid15009172\rsid15165843}
{\*\generator Microsoft Word 10.0.4219;}{\info{\author No}{\operator No}{\creatim\yr2006\mo10\dy17\hr21\min21}{\revtim\yr2007\mo2\dy6\hr21\min17}{\version4}{\edmins0}{\nofpages1}{\nofwords21}{\nofchars135}{\*\company Name}{\nofcharsws155}{\vern16469}}
\margl1417\margr1417\margt1417\margb1134\ltrsect \widowctrl\ftnbj\aenddoc\hyphhotz425\noxlattoyen\expshrtn\noultrlspc\dntblnsbdb\nospaceforul\hyphcaps0\horzdoc\dghspace120\dgvspace120\dghorigin1701\dgvorigin1984\dghshow0\dgvshow3
\jcompress\viewkind4\viewscale193\viewzk2\nolnhtadjtbl\rsidroot10506351 \fet0\ltrpar \sectd \ltrsect\linex0\sectdefaultcl\sftnbj {\*\pnseclvl1\pnucrm\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl2\pnucltr\pnqc\pnstart1\pnindent720\pnhang 
{\pntxta .}}{\*\pnseclvl3\pndec\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl4\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxta )}}{\*\pnseclvl5\pndec\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl6
\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl7\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl8\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl9
\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}\pard\plain \ltrpar\ql \li0\ri0\nowidctlpar\faauto\rin0\lin0\itap0 \rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1031\langfe1031\cgrid\langnp1031\langfenp1031 {\rtlch \af1\afs20 \ltrch 
\f1\fs20\insrsid10506351 Test
\par }{\rtlch \af1\afs20 \ltrch \f1\fs20\insrsid15165843 \'f6\'e4\'fc\'d6\'c4\'dc\'df}{\rtlch \af1\afs20 \ltrch \f1\fs20\insrsid10506351 
\par plain umlauts: \'f6\'e4\'fc\'d6\'c4\'dc\'df
\par this is A wordgame
\par }{\rtlch \ab\af1\afs20 \ltrch \b\f1\fs20\insrsid10506351 bold
\par }{\rtlch \ai\af1\afs20 \ltrch \i\f1\fs20\insrsid10506351 italic
\par }{\rtlch \af1\afs20 \ltrch \f1\fs20\ul\insrsid10506351 underline
\par }{\rtlch \af1\afs20 \ltrch \f1\fs20\super\insrsid10506351 high
\par }{\rtlch \af1\afs20 \ltrch \f1\fs20\sub\insrsid10506351 low
\par }}
";

        public static string TocAndPmTags => @"
{\rtf1\ansi\deff0{\info{\doccomm generated by an Adobe application}}{\fonttbl{\f0\froman Times New Roman;}{\f1\froman Times New Roman;}}{\colortbl;\red0\blue0\green0 ;}{\stylesheet
{\s1 \cf1\fs60\b Headline;}}
\sectd\pard\plain\hyphhotz720 {\tc\pard\plain\s1\fs60\b <Headline>the disapeared headline}\s1 \plain\fs60\b \par
\pard\plain <>above this should be written: the disapeared headline}
        ";
    }
}