//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limaki.View.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Limaki.View.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] LogoDrop32 {
            get {
                object obj = ResourceManager.GetObject("LogoDrop32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] LogoDrop32Icon {
            get {
                object obj = ResourceManager.GetObject("LogoDrop32Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] SubWin {
            get {
                object obj = ResourceManager.GetObject("SubWin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] SubWinIcon {
            get {
                object obj = ResourceManager.GetObject("SubWinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
